# A configuration file for how this stuff is to be deployed with
# Fabric.

# which code to deploy, this'll allow is to do a git clone in
# /var/praekelt which'll give us a `django-skeleton`
# (or whatever repo name) folder there.
repository:
    url: git://github.com/praekelt/django-skeleton.git
    branch: feature/issue-2-fabfile

# on which hosts this should happen
hosts:
    - kraken.za.prk-host.net

# These environment variables will be available to stuff being
# run by supervisord and by the handlers that run django management
# commands.
env:
    DATABASE_URL: 'postgres://postgres@localhost:5432/skeleton'

# this will allow us to generate supervisord config files, not sure if
# we want this in fab or in puppet.
processes:
    # allowed values are lists of commands or one line commands.
    web:
        - gunicorn --bind 0.0.0.0:8000 skeleton.wsgi
        - gunicorn --bind 0.0.0.0:8001 skeleton.wsgi
        - gunicorn --bind 0.0.0.0:8002 skeleton.wsgi
        - gunicorn --bind 0.0.0.0:8003 skeleton.wsgi
    celery: python manage.py celery worker --loglevel=info

post_clone:
    - 'if psql --user postgres --host localhost -l | grep -w skeleton; then true;
       else createdb --user postgres --host localhost --port 5432 -E UNICODE -T template0 skeleton; fi'
    - pip install -r requirements.pip
    - python manage.py syncdb --migrate --noinput
    - python manage.py collectstatic --noinput

post_pull:
    - pip install -r requirements.pip
    - python manage.py syncdb --migrate --noinput
    - python manage.py collectstatic --noinput
